
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fabricio 
  password: PostgreSQL_Role_Password

development:
  <<: *default
  database: app_rails_mirandaw_development

test:
  <<: *default
  database: app_rails_mirandaw_test


production:
  <<: *default
  database: app_rails_mirandaw_production
  username: app_rails_mirandaw
  password: <%= ENV['APP_RAILS_MIRANDAW_DATABASE_PASSWORD'] %>
